proxy_host: "0.0.0.0"
proxy_port: 53
fake_response:
  host: "0.0.0.0"
  ttl: 666
replace_dns:
  "crm.bucheon.uz.": "144.44.41.232"
dns_forwarders:
  host: "8.8.8.8"
  port: 53

black_list_domains:
  - "pornhub.com"
load_black_list: True
# Если слово из списка присутствует в доменном имени которое загружается из backlist.txt
# тогда доменное имя не будет добавлено в базу данных.
# Данный фильтр работает только при загрузке базы данных из backlist.txt
allow_template_list:
  - "Надо указать доменное имя"